import QtQuick
import QtQuick.Layouts
import Quickshell
import Quickshell.Hyprland
import Quickshell.Io

import qs.Commons
import qs.Ui

BarWidget {
    id: root

    moduleName: "community.split-workspaces"

    /*
     * split-monitor-workspaces does not currently expose its Lua
     * workspace_count to Quickshell/QML.
     *
     * Keep this equal to:
     *
     *   smw.setup({
     *       workspace_count = 9,
     *   })
     *
     * The rest of the widget is monitor-aware.
     */
    property int workspaceCount: 9

    /*
     * The first five workspaces are always visible.
     * Higher workspaces appear when occupied or focused.
     */
    property int permanentWorkspaceCount: 5

    readonly property var currentMonitor: Hyprland.monitorFor(root.screen)

    /*
     * The workspace IDs generated by split-monitor-workspaces are
     * contiguous globally according to monitor priority.
     *
     * We derive the beginning of this monitor's range from the
     * workspaces Hyprland currently reports.
     */
    function monitorWorkspaces() {
        var result = []
        var monitor = root.currentMonitor

        if (!monitor)
            return result

        var values = Hyprland.workspaces.values

        for (var i = 0; i < values.length; i++) {
            var workspace = values[i]

            if (!workspace || !workspace.monitor)
                continue

            if (workspace.monitor.id === monitor.id)
                result.push(workspace)
        }

        return result
    }

    /*
     * Determine the first global workspace ID belonging to this monitor.
     *
     * With:
     *
     *   workspace_count = 9
     *
     * this gives:
     *
     *   first monitor -> 1
     *   second monitor -> 10
     *   third monitor -> 19
     *
     * This assumes the standard contiguous SMW numbering.
     */
    function monitorOffset() {
        var monitor = root.currentMonitor

        if (!monitor)
            return 0

        var monitors = Hyprland.monitors.values

        /*
         * We cannot directly ask SMW for monitor_priority because that
         * configuration lives in its Lua environment.
         *
         * Instead, order monitors by Hyprland's monitor list.
         *
         * For the normal two-monitor setup this corresponds to the
         * standard SMW ordering when no explicit priority is configured.
         */
        var ordered = []

        for (var i = 0; i < monitors.length; i++) {
            if (monitors[i])
                ordered.push(monitors[i])
        }

        ordered.sort(function(a, b) {
            return a.id - b.id
        })

        for (var j = 0; j < ordered.length; j++) {
            if (ordered[j].id === monitor.id)
                return j * root.workspaceCount
        }

        return 0
    }

    /*
     * Global workspace ID -> local monitor workspace number.
     */
    function localWorkspaceId(globalId) {
        return globalId - monitorOffset()
    }

    /*
     * Local workspace number -> global Hyprland workspace ID.
     */
    function globalWorkspaceId(localId) {
        return monitorOffset() + localId
    }

    function workspaceById(globalId) {
        var values = Hyprland.workspaces.values

        for (var i = 0; i < values.length; i++) {
            if (values[i] && values[i].id === globalId)
                return values[i]
        }

        return null
    }

    function workspaceOccupied(globalId) {
        var toplevels = Hyprland.toplevels.values

        for (var i = 0; i < toplevels.length; i++) {
            var toplevel = toplevels[i]

            if (!toplevel || !toplevel.workspace)
                continue

            if (toplevel.workspace.id === globalId)
                return true
        }

        return false
    }

    function workspaceFocused(globalId) {
        var focused = Hyprland.focusedWorkspace

        return focused !== null &&
               focused.id === globalId
    }

    /*
     * Return local workspace numbers that should actually be displayed.
     *
     * 1..5 always exist visually.
     * 6..N only appear if occupied or focused.
     */
    function workspaceIds() {
        var ids = []

        var max = Math.max(
            1,
            root.workspaceCount
        )

        var permanent = Math.min(
            root.permanentWorkspaceCount,
            max
        )

        for (var localId = 1; localId <= permanent; localId++)
            ids.push(localId)

        for (
            var extra = permanent + 1;
            extra <= max;
            extra++
        ) {
            var globalId = root.globalWorkspaceId(extra)

            if (
                root.workspaceOccupied(globalId) ||
                root.workspaceFocused(globalId)
            ) {
                ids.push(extra)
            }
        }

        return ids
    }

    function focusWorkspace(localId) {
        var globalId = root.globalWorkspaceId(localId)

        if (!root.bar)
            return

        /*
         * Use Hyprland's normal dispatch path. The global ID is important:
         *
         * monitor A local 3 -> global 3
         * monitor B local 3 -> global 12
         */
        root.bar.run(
            "hyprctl dispatch workspace " +
            Util.shellQuote(String(globalId))
        )
    }

    readonly property real trailingGap:
        root.vertical ? 0 : Style.spaceReal(1.5)

    implicitWidth:
        grid.implicitWidth + trailingGap

    implicitHeight:
        grid.implicitHeight

    GridLayout {
        id: grid

        anchors.fill: parent
        anchors.rightMargin: root.trailingGap

        columns:
            root.vertical
                ? 1
                : root.workspaceIds().length

        columnSpacing:
            root.vertical
                ? 0
                : Style.space(1)

        rowSpacing:
            root.vertical
                ? Style.space(2)
                : 0

        Repeater {
            model: root.workspaceIds()

            WidgetButton {
                required property int modelData

                readonly property int localId: modelData
                readonly property int globalId:
                    root.globalWorkspaceId(localId)

                readonly property bool occupied:
                    root.workspaceOccupied(globalId)

                readonly property bool focused:
                    root.workspaceFocused(globalId)

                bar: root.bar

                text:
                    focused
                        ? "\uDB85\uDCFB"
                        : (
                            localId === 10
                                ? "0"
                                : String(localId)
                        )

                opacity:
                    occupied || focused
                        ? 1
                        : 0.5

                horizontalMargin: 6
                verticalPadding: 6

                fixedWidth:
                    root.vertical
                        ? root.barSize
                        : Style.space(20)

                fixedHeight:
                    root.barSize

                onPressed:
                    root.focusWorkspace(localId)
            }
        }
    }
}
